import Head from 'next/head';
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Keke-Tweet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto">
        {/* Barre latérale */}
        <Sidebar />

        {/* Principale */}
        <Feed />

        {/* Widgets */}

        {/* Moale */}
      </main>
    </div>
  );
}
